#!/usr/bin/env python3
"""Claim and release files so only one person edits them at a time.

Works in PowerShell, IntelliJ's terminal, and Command Prompt.
No chmod and no bash required.

Usage (from the repo root):
  python scripts/checkout.py status
  python scripts/checkout.py claim path/to/file
  python scripts/checkout.py release path/to/file
  python scripts/checkout.py release --force path/to/file
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def run(args: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(args, check=check, text=True, capture_output=True)


def git(*args: str, check: bool = True) -> str:
    result = run(["git", *args], check=check)
    return (result.stdout or "").strip()


def repo_root() -> Path:
    try:
        return Path(git("rev-parse", "--show-toplevel")).resolve()
    except subprocess.CalledProcessError:
        die("Run this from inside a git repository.")


def die(message: str, code: int = 1) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(code)


def identity(root: Path) -> tuple[str, str]:
    name = git("-C", str(root), "config", "user.name", check=False)
    email = git("-C", str(root), "config", "user.email", check=False)
    if not name or not email:
        die("Set git user.name and user.email first.")
    return name, email


def current_branch(root: Path) -> str:
    return git("-C", str(root), "rev-parse", "--abbrev-ref", "HEAD")


def normalize(root: Path, raw: str) -> str:
    candidate = Path(raw)
    if not candidate.is_absolute():
        candidate = Path.cwd() / candidate
    candidate = candidate.resolve()
    try:
        rel = candidate.relative_to(root)
    except ValueError:
        die(f"Path is outside the repository: {raw}")
    return rel.as_posix()


def lock_path(root: Path, rel: str) -> Path:
    return root / ".checkouts" / f"{rel}.lock"


def read_lock(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        data[key.strip()] = value.strip()
    return data


def write_lock(path: Path, rel: str, name: str, email: str, branch: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    since = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    path.write_text(
        "\n".join(
            [
                f"file: {rel}",
                f"user: {name}",
                f"email: {email}",
                f"since: {since}",
                f"branch: {branch}",
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )


def rebuild_markdown(root: Path) -> None:
    lock_root = root / ".checkouts"
    lock_root.mkdir(parents=True, exist_ok=True)
    rows = []
    for path in sorted(lock_root.rglob("*.lock")):
        info = read_lock(path)
        rel = info.get("file") or path.relative_to(lock_root).as_posix()[:-5]
        rows.append(
            (
                rel,
                info.get("user", "?"),
                info.get("since", "?"),
                info.get("branch", "?"),
            )
        )

    lines = [
        "# Active checkouts",
        "",
        "This file is generated by `python scripts/checkout.py`.",
        "Do not edit it by hand.",
        "",
    ]
    if not rows:
        lines.append("No files are checked out.")
    else:
        lines += [
            "| File | Who | Since (UTC) | Branch |",
            "|---|---|---|---|",
        ]
        for rel, user, since, branch in rows:
            lines.append(f"| `{rel}` | {user} | {since} | `{branch}` |")
        lines.append("")
        lines.append(f"{len(rows)} file(s) checked out.")
    (root / "CHECKOUTS.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8", newline="\n"
    )


def pull_latest(root: Path) -> None:
    print("Pulling latest from origin...")
    branch = current_branch(root)
    run(["git", "-C", str(root), "fetch", "origin"], check=True)
    verify = run(
        ["git", "-C", str(root), "rev-parse", "--verify", f"origin/{branch}"],
        check=False,
    )
    if verify.returncode == 0:
        run(
            [
                "git",
                "-C",
                str(root),
                "pull",
                "--rebase",
                "--autostash",
                "origin",
                branch,
            ],
            check=True,
        )
    else:
        print(f"No origin/{branch} yet; skipping pull.")


def commit_and_push(root: Path, message: str) -> None:
    run(["git", "-C", str(root), "add", "--", "CHECKOUTS.md", ".checkouts"], check=True)
    run(["git", "-C", str(root), "add", "-A", "--", ".checkouts"], check=True)
    staged = run(["git", "-C", str(root), "diff", "--cached", "--quiet"], check=False)
    if staged.returncode == 0:
        print("Nothing changed.")
        return
    run(["git", "-C", str(root), "commit", "-m", message], check=True)
    pushed = run(["git", "-C", str(root), "push", "origin", "HEAD"], check=False)
    if pushed.returncode != 0:
        print(pushed.stdout)
        print(pushed.stderr, file=sys.stderr)
        die(
            "Push failed. Someone else may have claimed a file at the same time.\n"
            "Run: git pull --rebase\n"
            "Then run the command again."
        )


def cmd_status(root: Path, target: str | None) -> None:
    rebuild_markdown(root)
    if target:
        rel = normalize(root, target)
        path = lock_path(root, rel)
        if not path.is_file():
            print(f"{rel} is free.")
            return
        info = read_lock(path)
        print(rel)
        print(f"  who:    {info.get('user', '?')} <{info.get('email', '?')}>")
        print(f"  since:  {info.get('since', '?')}")
        print(f"  branch: {info.get('branch', '?')}")
        return
    print((root / "CHECKOUTS.md").read_text(encoding="utf-8"), end="")


def cmd_claim(root: Path, target: str) -> None:
    name, email = identity(root)
    rel = normalize(root, target)
    if not (root / rel).exists():
        print(f"Warning: {rel} does not exist yet. Claiming the path anyway.")
    pull_latest(root)
    path = lock_path(root, rel)
    if path.is_file():
        info = read_lock(path)
        if info.get("email") == email:
            print(
                f"You already have {rel} checked out "
                f"(since {info.get('since')} on {info.get('branch')})."
            )
            return
        die(
            f"BLOCKED: {rel} is checked out by {info.get('user')} <{info.get('email')}>\n"
            f"         since {info.get('since')} on branch {info.get('branch')}\n"
            f"Ask them to run: python scripts/checkout.py release {rel}"
        )
    write_lock(path, rel, name, email, current_branch(root))
    rebuild_markdown(root)
    commit_and_push(root, f"checkout: claim {rel} ({name})")
    print()
    print(f"Checked out {rel} as {name}.")
    print(f"Edit the file, commit as usual, then run: python scripts/checkout.py release {rel}")


def cmd_release(root: Path, target: str, force: bool) -> None:
    name, email = identity(root)
    rel = normalize(root, target)
    pull_latest(root)
    path = lock_path(root, rel)
    if not path.is_file():
        print(f"{rel} is not checked out.")
        return
    info = read_lock(path)
    if info.get("email") != email and not force:
        die(
            f"BLOCKED: {rel} is checked out by {info.get('user')} <{info.get('email')}>, not you.\n"
            f"If that claim is stale, run: python scripts/checkout.py release --force {rel}"
        )
    path.unlink()
    # Drop empty folders under .checkouts, but keep .checkouts itself.
    checkouts = root / ".checkouts"
    for folder in sorted(checkouts.rglob("*"), reverse=True):
        if folder.is_dir() and not any(folder.iterdir()):
            folder.rmdir()
    rebuild_markdown(root)
    commit_and_push(root, f"checkout: release {rel} ({name})")
    print()
    print(f"Released {rel}.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Claim or release a file in this repo.")
    sub = parser.add_subparsers(dest="command", required=True)

    status = sub.add_parser("status", help="Show current checkouts")
    status.add_argument("path", nargs="?")

    claim = sub.add_parser("claim", help="Check out a file")
    claim.add_argument("path")

    release = sub.add_parser("release", help="Check a file back in")
    release.add_argument("--force", action="store_true", help="Release someone else's stale claim")
    release.add_argument("path")

    args = parser.parse_args()
    root = repo_root()
    if args.command == "status":
        cmd_status(root, args.path)
    elif args.command == "claim":
        cmd_claim(root, args.path)
    elif args.command == "release":
        cmd_release(root, args.path, args.force)


if __name__ == "__main__":
    main()
